console.log('Hello World');
var message;
message = 'Hello Typescript';
console.log(message);
//message = 30;
var bool = [true, false];
console.log(bool[1]);
//let a: string = 'hello';
//let a = 'hello';
//const bool = [true, false];
//const bool: boolean[] = [true, false];
