import aws from 'aws-sdk';
import db from '../dynamodbconfig';
import mapper from '../dynamodbmapper';
import {
    attribute,
    hashKey,
    rangeKey,
    table,
    autoGeneratedHashKey,
} from '@aws/dynamodb-data-mapper-annotations';


@table('birthdaycardsmodule9')
export class BirthdayCard {
  @autoGeneratedHashKey()
  _id?: string;
  @hashKey()
  title?: string;
  @attribute()
  material?: string;
  @attribute()
  picture?: string;
  @attribute()
  price?: number;
}


export function addBirthdayCard(title: string, material: string, picture: string, price: number) {
  mapper.put(Object.assign(new BirthdayCard, {title: title, material: material, picture: picture, price: price}))
    .then(objectSaved => {
      console.log(objectSaved)
    })
    .catch(err => {
      console.log(err, err.stack);
    })
  }

  export async function findBirthdayCard(title: string) {
    let user = await mapper.get(Object.assign(new BirthdayCard, {title: title}));
    return user
  }