import aws from 'aws-sdk';
import db from '../dynamo';
import mapper from '../dynamodbmapper';
import {
    attribute,
    hashKey,
    rangeKey,
    table,
    autoGeneratedHashKey,
} from '@aws/dynamodb-data-mapper-annotations';


@table('books')
export class Book {
  @hashKey()
  title?: string;
  @attribute()
  isbn?: string;
  @attribute()
  author?: string;
  @attribute()
  picture?: string;
  @attribute()
  providers?: string
}


export function createProduct(title: string, weight: number, price: number, amount: number, providers: string) {
  mapper.put(Object.assign(new Product, {title: title, weight: weight, price: price, amount: amount, providers: providers}))
    .then(objectSaved => {
      console.log(objectSaved)
    })
    .catch(err => {
      console.log(err, err.stack);
    })
  }

  export async function findProduct(title: string) {
    let user = await mapper.get(Object.assign(new Product, {title: title}));
    return user
  }