import aws from 'aws-sdk';
import db from '../dynamodbconfig';
import mapper from '../dynamodbmapper';
import {
    attribute,
    hashKey,
    rangeKey,
    table,
    autoGeneratedHashKey,
} from '@aws/dynamodb-data-mapper-annotations';


@table('module9Books')
export class Book {
  @autoGeneratedHashKey()
  _id?: string;
  @attribute()
  title?: string;
  @attribute()
  isbn?: string;
  @attribute()
  author?: string;
  @attribute()
  picture?: string;
  @attribute()
  price?: number;
}


export function addBook(title: string, isbn: string, author: string, picture: string, price: number) {
  mapper.put(Object.assign(new Book, {title: title, isbn: isbn, author: author, picture: picture, price: price}))
    .then(objectSaved => {
      console.log(objectSaved)
    })
    .catch(err => {
      console.log(err, err.stack);
    })
  }

export async function updateBook(id: string, title: string, isbn: string, author: string, picture: string, price: number) {
  try {
    await mapper.update(Object.assign(new Book, {_id: id, title: title, isbn: isbn, author: author, picture: picture, price: price }))
  } catch (e) {
    console.error(e);
  }
}

export async function fetchBook(id: string) {
  let book = await mapper.get(Object.assign(new Book, {_id: id}));
  return book;
}

export async function deleteBook(id: string) {
  try {
  await mapper.delete(Object.assign(new Book, {_id: id}));
} catch(e) {
  console.error(e);
}
}


  export async function findBook(id: string) {
    let user = await mapper.get(Object.assign(new Book, {id: id}));
    return user
  }

  export async function fetchBooks() {
    let books = [];
    for await (const item of mapper.scan(Book)) {
      //what is item, is it an object? a JSON string?
      books.push(item);
    }
    return books;
  }
